# Ejercicios de Numpy y Pandas básico:

Aquí podéis ver la importancia en términos de velocidad de manejar numpy vs pandas:

https://towardsdatascience.com/speed-testing-pandas-vs-numpy-ffbf80070ee7 

Aquí podéis encontrar un dataset amplio con el que jugar y testear grandes volúmenes de datos:

https://www.kaggle.com/datasets/zanjibar/100-million-data-csv 

In [1]:
import numpy as np
import pandas as pd

## 1 - Crea los siguientes Arrays:

### A - Un vector de 15 números aleatorios. Estos números deben estar comprendidos entre 42 y 1337.

In [16]:
ej1a = np.random.randint(42, 1338, 15)
ej1a

array([ 256,  941,  814, 1332,  866,  876,  764,  649,  798, 1117,  762,
        562, 1318, 1301, 1031])

In [17]:
(np.random.rand(15)*(1337-42))+42

array([  97.7694426 ,  590.5041933 ,  318.22210815, 1311.82880564,
        715.51366926,  565.53855405,  672.1621947 ,  271.30746526,
        768.34786409,  810.38419089,  644.38970246, 1290.35775963,
         81.52524307,  204.06330335,  668.72060471])

In [18]:
np.random.uniform(42,1338, 15)

array([ 961.8492144 ,  505.30261666,  840.68634518,  902.22359541,
         49.88306385,  821.63439647,   79.22580346,  610.7975392 ,
        609.63999286,  866.33609474,  278.66646017,  418.03181899,
        429.48917279, 1234.24864643,  703.59172685])

### B - Un vector de números enteros ordenados entre el 3 y el 33.

In [20]:
ej2 = np.arange(3,34)

### C - Un vector de 10 números que representen una progresión geométrica (escala logarítmica) entre 10 y 100 (recordad que Google es vuestro amigo).

### D - Crea una matriz de dimensiones 3 filas, 4 columnas y 5 de profundidad donde todos los elementos sean aleatorios.

In [41]:
ej1d = np.random.randn(5,3,4)
ej1d

array([[[-0.50529071, -0.37744437,  0.58559649, -0.75937042],
        [ 0.73920914, -0.35546675, -0.34223091,  1.35537986],
        [-1.43834704, -0.38161071,  1.66396555,  1.23692303]],

       [[ 0.97612486,  1.47816979,  0.38745912, -0.86817982],
        [ 0.1230736 ,  0.34613295, -0.69740511, -0.51402538],
        [-0.9722233 ,  0.68580744, -0.5343215 , -1.28540564]],

       [[ 0.62815489,  0.74368761, -0.23299302,  1.5545081 ],
        [-0.04058637,  0.70725743, -0.68946785,  0.45878894],
        [ 0.11015468, -0.1389014 , -0.45349131, -0.4276475 ]],

       [[-1.10977917,  0.48542962, -0.43190008, -2.06845478],
        [-0.02253655, -0.05587165,  0.81761164,  1.18448875],
        [-0.95333719, -0.18645256,  0.8209104 , -0.19679496]],

       [[ 0.11752171,  0.5110639 ,  0.75532741,  0.44859724],
        [ 1.75816911,  0.20600386, -2.07957338, -0.71767573],
        [ 0.98201717, -1.35587769, -0.84116184, -0.41969692]]])

### E - Genera un vector de 10 numeros aleatorios entre el 0 y el 1. Haz que los valores de dicho vector se vuelvan 0 si el número es menor de 0.5 y de 1 si el número es mayor o igual a 0.5.

In [23]:
ej1e = np.random.rand(10)
ej1e

array([0.55483655, 0.09421262, 0.34449814, 0.93238966, 0.63591952,
       0.37449833, 0.37443993, 0.0574374 , 0.51324312, 0.51767054])

In [26]:
(ej1e >= 0.5)*1

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 1])

### F - Genera una matriz de números aleatorios de dos filas y tres columnas y multiplicala matricialmente por si misma:

In [31]:
ej1f = np.random.randint(50, 75, (2,3))
ej1f

array([[53, 62, 50],
       [52, 67, 51]])

In [34]:
np.matmul(ej1f, ej1f.T)

array([[9153, 9460],
       [9460, 9794]])

In [36]:
ej1f @ ej1f.T

array([[9153, 9460],
       [9460, 9794]])

## Ejercicio 2: Realiza las siguientes operaciones

### A - Toma cualquier vector y transformalo en una serie de pandas.

In [40]:
pd.Series(ej1a)

0      256
1      941
2      814
3     1332
4      866
5      876
6      764
7      649
8      798
9     1117
10     762
11     562
12    1318
13    1301
14    1031
dtype: int32

### B - Toma cualquier array de más de una dimensión de los ejercicios anteriores y transfórmalo en un DataFrame.

In [44]:
ej1d[1]

array([[ 0.97612486,  1.47816979,  0.38745912, -0.86817982],
       [ 0.1230736 ,  0.34613295, -0.69740511, -0.51402538],
       [-0.9722233 ,  0.68580744, -0.5343215 , -1.28540564]])

In [45]:
ej2b = pd.DataFrame(ej1d[1])
ej2b

0         1         2         3
0  0.976125  1.478170  0.387459 -0.868180
1  0.123074  0.346133 -0.697405 -0.514025
2 -0.972223  0.685807 -0.534321 -1.285406

### C - Genera un DataFrame de números aleatorios entre 0 y 100 de 10 filas y 5 columnas.

In [52]:
ej2c = pd.DataFrame(np.random.rand(10,5)*100)
ej2c

0          1          2          3          4
0  19.081068  57.940147  82.448491  39.830403  63.910504
1  59.593970  79.598062  44.064419  23.917024  27.209365
2  63.739187  44.666865  73.164642  90.051003  64.010805
3  56.558334  17.790361  65.233377  78.272234  50.121845
4   7.555008  42.798388  17.292969  85.850281  12.443553
5  61.248017  87.882972  14.304193  63.676135  45.285030
6  66.763049  39.539460   3.223450   7.387332  88.769168
7  42.371866  58.591491  37.926913  75.511320  86.435065
8  10.636689  27.607737  61.772046  22.989664  74.343438
9  42.246606   3.691076   5.131537  62.388588  87.721430

### D - Cambia los nombres de las columnas del anterior Dataframe

In [54]:
ej2c.columns = ['hora', 'cierre', 'volumen', 'apertura', 'maximo']

In [55]:
ej2c

hora     cierre    volumen   apertura     maximo
0  19.081068  57.940147  82.448491  39.830403  63.910504
1  59.593970  79.598062  44.064419  23.917024  27.209365
2  63.739187  44.666865  73.164642  90.051003  64.010805
3  56.558334  17.790361  65.233377  78.272234  50.121845
4   7.555008  42.798388  17.292969  85.850281  12.443553
5  61.248017  87.882972  14.304193  63.676135  45.285030
6  66.763049  39.539460   3.223450   7.387332  88.769168
7  42.371866  58.591491  37.926913  75.511320  86.435065
8  10.636689  27.607737  61.772046  22.989664  74.343438
9  42.246606   3.691076   5.131537  62.388588  87.721430

### E - Cambia el índice del anterior dataframe para que sean años consecutivos después del 1990:

In [58]:
np.arange(len(ej2c))+1990

array([1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999])

In [59]:
ej2c.index = np.arange(len(ej2c))+1990

In [60]:
ej2c

hora     cierre    volumen   apertura     maximo
1990  19.081068  57.940147  82.448491  39.830403  63.910504
1991  59.593970  79.598062  44.064419  23.917024  27.209365
1992  63.739187  44.666865  73.164642  90.051003  64.010805
1993  56.558334  17.790361  65.233377  78.272234  50.121845
1994   7.555008  42.798388  17.292969  85.850281  12.443553
1995  61.248017  87.882972  14.304193  63.676135  45.285030
1996  66.763049  39.539460   3.223450   7.387332  88.769168
1997  42.371866  58.591491  37.926913  75.511320  86.435065
1998  10.636689  27.607737  61.772046  22.989664  74.343438
1999  42.246606   3.691076   5.131537  62.388588  87.721430

## Ejercicio 3: Toma la matriz del ejercicio 1-D anterior y devuelve las sumas de sus elementos:
-	Por filas
-	Por columnas
-	Por profundidad

## Ejercicio 4:  Crea un array de 365 de longitud que cumpla lo siguiente:
-	Longitud 365.
-	Primer elemento = 1
-	Cada elemento posterior es el resultado de incrementar el elemento anterior en un porcentaje aleatorio entre el +10% y el -10%.

Por ejemplo, si el número anterior fuese un 2, el elemento posterior sería cualquier número en el rango 1,8-2,2 (+-10%)

In [89]:
lista_objetivo = [1]

for numero in range(1,365):
    variacion = np.random.uniform(-0.1,0.1)
    numero = lista_objetivo[-1]
    nuevo_numero = numero * (1+variacion)
    lista_objetivo.append(nuevo_numero)

lista_objetivo

[1,
 1.070911292818376,
 1.1081726585489697,
 1.1416367649066161,
 1.1090105819741976,
 1.0566854651609254,
 1.053681446194143,
 0.9813201296464692,
 0.9566351343746414,
 0.9231642518378449,
 0.9207374990994129,
 1.0069080593380664,
 1.0608498769342736,
 1.166502489150407,
 1.1031319405290754,
 1.0620637871649232,
 1.1660396138106128,
 1.114950822883945,
 1.0593819942619558,
 1.037242937853989,
 0.9917590414290013,
 0.9547834533478159,
 0.9077883331021445,
 0.991184450568264,
 1.0069068650000441,
 0.9358250179712537,
 0.9741805174412099,
 0.878195144704807,
 0.9294738737887023,
 0.8580303370173366,
 0.8697347164269421,
 0.8376991964323766,
 0.8710368461119868,
 0.9040606448495668,
 0.9270495137553366,
 0.9997506504509461,
 0.9801761527357523,
 1.0531988490309863,
 1.0762272754885598,
 1.0051830317177464,
 1.0539984932412332,
 1.0955194712057204,
 1.052639321058273,
 1.0716644719078932,
 0.9896563224973348,
 0.9434286996821908,
 0.9524148501014518,
 0.8770669741879238,
 0.87709128128995

In [90]:
len(lista_objetivo)

365

## Ejercicio 5: Ahora crea un array de la misma longitud que consista en ir repitiendo los números del 0 al 6 hasta que rellene la longitud (puede que no cuadre perfectamente, no tiene por qué terminar en 6).

In [ ]:
[0,1,2,3,4,5,6,0,1,2,3,4,5,6............]

## Ejercicio 6: Toma el array del ejercicio anterior y el que acabas de crear y crea un nuevo array en el que solo se muestren los datos del array del ejercicio 4 que no estén en la misma posición en que en el array del ejercicio 5 existe un ‘6’.

### Ejemplo: Usando la posición donde en el array del Ej5 haya un 6 (posición 7, 14,...) debemos **filtrar** el array del Ej4 para no obtener esos datos:

**Array ej 4:**

[1.         0.91765149 0.87665302 0.82558682 0.87322844 0.93757515
 **0.99255131** 1.06506252 1.16221735 1.13299229 1.10232511 1.09412955
 1.0107777  **1.0787682**  1.03595279 1.10241797 1.12717531 1.22887874 ...

**Array ej 5:**

[0 1 2 3 4 5 **6** 0 1 2 3 4 5 **6** 0 1 2 3 4 5 **6** ...

## Ejercicios Numpy Finance:

In [2]:
import numpy_financial as npf

### **1.-** Crea una función que calcule lo que te queda por pagar de hipoteca:

- Parámetros:
    - Cantidad de la hipoteca
    - Pago mensual
    - Cantidad pagada
    - Tasa de interés

### **2.-** Calcula el TIR :
|Mes|Cantidad|
|----|---|
|Enero|-1500|
|Febrero|300|
|Marzo|75|
|Abril|200|
|Mayo|300|
|Junio|56|
|Julio|98|
|Agosto|290|
|Septiembre|130|
|Octubre|160|
|Noviembre|120|
|Diciembre|100|


### **3.-** ¿Cuál es el valor actual (por ejemplo, la inversión inicial) de una inversión que debe ascender a 15692.93 € después de 10 años de ahorrar 100 € cada mes? Supongamos que el tipo de interés es del 5% (anual).
