# Ejercicios de Numpy y Pandas básico:

In [1]:
import numpy as np
import pandas as pd

## 1 - Crea los siguientes Arrays:

### A - Un vector de 15 números aleatorios. Estos números deben estar comprendidos entre 42 y 1337.

In [2]:
ej1a = np.random.randint(42, 1338, 15)
ej1a

array([ 989,  149, 1264, 1204,  110,  414,  623,  925,  298, 1334,  613,
        149, 1244,  742,  272])

In [3]:
# Alternativa:
ej1a = np.random.rand(15)*(1338-42)+42
ej1a

array([ 613.04746663,  282.52147654,  994.8252585 , 1220.31073183,
        929.80313632, 1282.95301578,  590.85776428,  916.7881383 ,
        607.09534445,  989.5116991 ,  362.19538429,  714.19124061,
        673.14839684,  209.18928066, 1208.47785733])

### B - Un vector de números enteros ordenados entre el 3 y el 33.

In [4]:
ej1b = np.arange(3,34)
ej1b

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

### C - Un vector de 10 números que representen una progresión geométrica (escala logarítmica) entre 10 y 100 (recordad que Google es vuestro amigo).

In [5]:
ej1c = np.geomspace(10, 100, 10)
ej1c

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

### D - Crea una matriz de dimensiones 3 filas, 4 columnas y 5 de profundidad donde todos los elementos sean aleatorios.

In [6]:
ej1d = np.random.randn(5, 3, 4)
ej1d

array([[[ 1.04564534,  0.42455634,  0.1480201 ,  0.05587572],
        [ 0.62406836, -0.39517078,  0.37398914, -0.37735355],
        [ 0.5411916 ,  2.28916742, -0.61022887,  0.28812783]],

       [[ 0.69731226, -2.07414957, -1.09407313,  0.35635663],
        [-0.76991316, -0.55566485, -0.20934215, -0.16708503],
        [ 0.3364859 , -0.1435826 ,  1.80103811,  0.09693373]],

       [[-0.51320611,  0.77689141,  2.54751053,  0.19416852],
        [ 1.51184773,  0.57519582,  0.2700805 , -1.19424657],
        [ 0.47689574,  0.00707854,  0.0225578 , -1.45974865]],

       [[ 0.91438586,  0.01375954, -1.04511229,  1.04889798],
        [ 0.65029033, -0.52127146, -1.45467194, -0.89097388],
        [-0.64800264,  0.6075667 , -0.40842863,  0.90089209]],

       [[-1.38211933, -0.07850065, -0.02034065, -0.3785164 ],
        [ 0.08561739, -1.0750763 , -0.70043345, -0.5172402 ],
        [ 0.36864423,  2.33331486, -1.09586307, -1.50150365]]])

### E - Genera un vector de 10 numeros aleatorios entre el 0 y el 1. Haz que los valores de dicho vector se vuelvan 0 si el número es menor de 0.5 y de 1 si el número es mayor o igual a 0.5.

In [7]:
ej1e = np.random.rand(10)
print(ej1e)
(ej1e>0.5)*1

[0.52275249 0.33539508 0.73911801 0.51758473 0.76641392 0.41263429
 0.49903382 0.35913969 0.07099052 0.72837419]


array([1, 0, 1, 1, 1, 0, 0, 0, 0, 1])

### F - Genera una matriz de números aleatorios de dos filas y tres columnas y multiplicala matricialmente por si misma:

In [8]:
ej1f = np.random.randint(0, 100, (2, 3))
ej1f

array([[17, 51, 22],
       [47, 76, 10]])

In [9]:
ej1f @ ej1f.T

array([[3374, 4895],
       [4895, 8085]])

In [10]:
np.matmul(ej1f, ej1f.T)

array([[3374, 4895],
       [4895, 8085]])

In [11]:
ej1f*ej1f

array([[ 289, 2601,  484],
       [2209, 5776,  100]])

## Ejercicio 2: Realiza las siguientes operaciones

### A - Toma cualquier vector y transformalo en una serie de pandas.

In [12]:
ej2a = pd.Series(ej1a)
ej2a

0      613.047467
1      282.521477
2      994.825258
3     1220.310732
4      929.803136
5     1282.953016
6      590.857764
7      916.788138
8      607.095344
9      989.511699
10     362.195384
11     714.191241
12     673.148397
13     209.189281
14    1208.477857
dtype: float64

### B - Toma cualquier array de más de una dimensión de los ejercicios anteriores y transfórmalo en un DataFrame.

In [13]:
#ej2b = pd.DataFrame(ej1d)

ej2b = pd.DataFrame(ej1d[1])
ej2b

0         1         2         3
0  0.697312 -2.074150 -1.094073  0.356357
1 -0.769913 -0.555665 -0.209342 -0.167085
2  0.336486 -0.143583  1.801038  0.096934

### C - Genera un DataFrame de números aleatorios entre 0 y 100 de 10 filas y 5 columnas.

In [14]:
ej2c = pd.DataFrame(np.random.randint(0, 100, (10, 5)))
ej2c

0   1   2   3   4
0  13  65  60  94   0
1   3  21  55  43  73
2   3  70   9  77  55
3  68  38  38  61  55
4  53  45  18  39  84
5  32  19  14  11   8
6  52  48  15  51  21
7  90  92  23  82  59
8   5  43  13   9  68
9  24  24  40  66  61

### D - Cambia los nombres de las columnas del anterior Dataframe

In [15]:
ej2d = ej2c.copy()
ej2d.columns = ['A', 'B', 'C', 'D', 'E']
ej2d

A   B   C   D   E
0  13  65  60  94   0
1   3  21  55  43  73
2   3  70   9  77  55
3  68  38  38  61  55
4  53  45  18  39  84
5  32  19  14  11   8
6  52  48  15  51  21
7  90  92  23  82  59
8   5  43  13   9  68
9  24  24  40  66  61

### E - Cambia el índice del anterior dataframe para que sean años consecutivos después del 1990:

In [16]:
ej2e = ej2d.copy()
ej2e.index = np.arange(len(ej2e))+1990
ej2e

A   B   C   D   E
1990  13  65  60  94   0
1991   3  21  55  43  73
1992   3  70   9  77  55
1993  68  38  38  61  55
1994  53  45  18  39  84
1995  32  19  14  11   8
1996  52  48  15  51  21
1997  90  92  23  82  59
1998   5  43  13   9  68
1999  24  24  40  66  61

## Ejercicio 3: Toma la matriz del ejercicio 1-D anterior y devuelve las sumas de sus elementos:
-	Por filas
-	Por columnas
-	Por profundidad

In [17]:
ej_2_filas = ej1d.sum(axis=2)
ej_2_filas

array([[ 1.6740975 ,  0.22553316,  2.50825798],
       [-2.11455381, -1.70200518,  2.09087514],
       [ 3.00536435,  1.16287748, -0.95321657],
       [ 0.93193108, -2.21662695,  0.45202751],
       [-1.85947703, -2.20713256,  0.10459238]])

In [18]:
ej_2_columnas = ej1d.sum(axis=1)
ej_2_columnas

array([[ 2.2109053 ,  2.31855298, -0.08821963, -0.03335   ],
       [ 0.263885  , -2.77339701,  0.49762283,  0.28620534],
       [ 1.47553736,  1.35916577,  2.84014884, -2.4598267 ],
       [ 0.91667355,  0.10005477, -2.90821286,  1.05881619],
       [-0.9278577 ,  1.17973791, -1.81663717, -2.39726025]])

In [19]:
ej_2_profundidad = ej1d.sum(axis=0)
ej_2_profundidad

array([[ 0.76201802, -0.93744293,  0.53600455,  1.27678245],
       [ 2.10191065, -1.97198758, -1.72037789, -3.14689923],
       [ 1.07521484,  5.09354493, -0.29092466, -1.67529866]])

## Ejercicio 4:  Crea un array de 365 de longitud que cumpla lo siguiente:
-	Longitud 365.
-	Primer elemento = 1
-	Cada elemento posterior es el resultado de incrementar el elemento anterior en un porcentaje aleatorio entre el +10% y el -10%.

Por ejemplo, si el número anterior fuese un 2, el elemento posterior sería cualquier número en el rango 1,8-2,2 (+-10%)

In [20]:
lista_objetivo = [1]

for i in range(1,365):
  aleat = np.random.uniform(-0.1,0.1)
  lista_objetivo.append(lista_objetivo[-1]*(1+aleat))

ej_4 = np.array(lista_objetivo)
print(ej_4[:10])
ej_4.shape

[1.         0.92965906 0.97822295 0.89310433 0.92488059 0.88372133
 0.90640774 0.9692908  0.87910522 0.91667392]


(365,)

## Ejercicio 5: Ahora crea un array de la misma longitud que consista en ir repitiendo los números del 0 al 6 hasta que rellene la longitud (puede que no cuadre perfectamente, no tiene por qué terminar en 6).

In [21]:
mini_array = np.arange(0,7)
print(f' Array base: {mini_array}')

# Si lo multiplicamos, multiplicamos sus elementos, no queremos esto sino repetirlo.
# Podemos repetir las listas, por lo que transformandolo a lista y multiplicandolo por el numero de veces que queremos repetirlo, lo conseguimos.
array = list(mini_array)*int(365/7+1)
# Puede que nos hayamos pasado, por lo que cortamos el array a 365 elementos.
array = np.array(array[:365])
print(f' Array repetido: {array}')

 Array base: [0 1 2 3 4 5 6]
 Array repetido: [0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1
 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3
 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5
 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0
 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2
 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4
 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6
 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1
 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3
 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0 1 2 3 4 5 6 0]


In [30]:
# Alternativa: Un array de 0 a 6 tiene longitud 7
mini_array = np.arange(0,7)

# Por lo tanto necesitamos 365/7 veces esto
full_array = np.tile(mini_array, int(365/7+1))
full_array = full_array[:365]
full_array

array([0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0,
       1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2,
       3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3,
       4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4,
       5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5,
       6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6,
       0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0,
       1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2,
       3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3,
       4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4,
       5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5,
       6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6,

## Ejercicio 6: Toma el array del ejercicio anterior y el que acabas de crear y crea un nuevo array en el que solo se muestren los datos del array del ejercicio 4 que no estén en la misma posición en que en el array del ejercicio 5 existe un ‘6’.

### Ejemplo: Usando la posición donde en el array del Ej5 haya un 6 (posición 7, 14,...) debemos **filtrar** el array del Ej4 para no obtener esos datos:

**Array ej 4:**

[1.         0.91765149 0.87665302 0.82558682 0.87322844 0.93757515
 **0.99255131** 1.06506252 1.16221735 1.13299229 1.10232511 1.09412955
 1.0107777  **1.0787682**  1.03595279 1.10241797 1.12717531 1.22887874 ...

**Array ej 5:**

[0 1 2 3 4 5 **6** 0 1 2 3 4 5 **6** 0 1 2 3 4 5 **6** ...

In [23]:
ej_4[:10]

array([1.        , 0.92965906, 0.97822295, 0.89310433, 0.92488059,
       0.88372133, 0.90640774, 0.9692908 , 0.87910522, 0.91667392])

In [24]:
ej_6 = ej_4[array != 6]
ej_6

array([1.        , 0.92965906, 0.97822295, 0.89310433, 0.92488059,
       0.88372133, 0.9692908 , 0.87910522, 0.91667392, 0.94854296,
       0.93179238, 1.02180456, 1.10103647, 1.12701435, 1.18390851,
       1.24540854, 1.285804  , 1.29070703, 1.21993804, 1.28348285,
       1.18501817, 1.16429059, 1.20407154, 1.27901163, 1.21992561,
       1.20425492, 1.16745008, 1.27623986, 1.27915086, 1.38780477,
       1.34857912, 1.27342606, 1.318038  , 1.38690104, 1.42847213,
       1.44023207, 1.33718297, 1.39644381, 1.5140723 , 1.49644671,
       1.59058534, 1.50086023, 1.53805665, 1.44804325, 1.48323992,
       1.3863042 , 1.34095066, 1.21186463, 1.14111411, 1.07618551,
       1.16637174, 1.19035483, 1.09321352, 1.0142659 , 1.07828474,
       1.05100679, 0.95046918, 0.87784525, 0.87096568, 0.9226667 ,
       0.95500988, 0.98468117, 0.96680128, 1.04735125, 1.01415351,
       0.97324395, 0.89035225, 0.92907711, 0.97015321, 1.02788244,
       1.06622891, 0.96925013, 0.87559497, 0.84943603, 0.83238

## Ejercicios Numpy Finance:

In [25]:
import numpy_financial as npf

### **1.-** Crea una función que calcule lo que te queda por pagar de hipoteca:

- Parámetros:
    - Cantidad de la hipoteca
    - Pago mensual
    - Cantidad pagada
    - Tasa de interés

In [26]:
# Función que calcule lo que queda de pagar de hipoteca en función de cantidad inicial, años pago mensual, interés y número de meses:
def hipoteca(cantidad_inicial, años, interes, meses_restantes):
    pago_mensual = npf.pmt(interes/12, años*12, cantidad_inicial)
    print(f"El pago mensual es de {round(pago_mensual, 2)} €")
    cuotas_restantes = pago_mensual * meses_restantes
    print(f"Quedan {round(cuotas_restantes,2)} € por pagar")
    return cuotas_restantes
hipoteca(100000, 30, 0.03, 12*10)

El pago mensual es de -421.6 €
Quedan -50592.48 € por pagar


-50592.48404753471

### **2.-** Calcula el TIR :
|Mes|Cantidad|
|----|---|
|Enero|-1500|
|Febrero|300|
|Marzo|75|
|Abril|200|
|Mayo|300|
|Junio|56|
|Julio|98|
|Agosto|290|
|Septiembre|130|
|Octubre|160|
|Noviembre|120|
|Diciembre|100|


In [27]:
flujos = [-1500, 300, 75, 200, 300, 56, 98, 290, 130, 160, 120, 100]

In [28]:
# La funcion npf.irr(flujos) calcula la tasa interna de retorno de una serie de flujos de caja
npf.irr(flujos)
    

0.03853247830660611

### **3.-** ¿Cuál es el valor actual (por ejemplo, la inversión inicial) de una inversión que debe ascender a 15692.93 € después de 10 años de ahorrar 100 € cada mes? Supongamos que el tipo de interés es del 5% (anual).


In [29]:
# La función Present Value (PV) nos permite calcular el valor presente de una serie de flujos de caja.
npf.pv(0.05/12, 10*12, -100, 15692.93)  

-100.00067131625819