# Numpy: Array

- Necesitamos tener pip instalado, conda lo tiene instalado 
- En caso de no tenerlo se haría desde terminal con:```
                                        pip install numpy
                                        ```
- Desde celda ```
            !pip install numpy
            ```

In [2]:
import numpy as np
np.version.version

'1.24.3'

In [10]:
!pip install numpy --upgrade --user

- Numpy se suele importar con el nombre np

## ¿Por qué usamos los arrays?

- La principal motivación es su facilidad de uso para realizar operaciones matemáticas, mejores que las listas.
- La velocidad de computo, podemos hacer cálculos vectoriales :)

In [5]:
[1,2,3,4,5,6,7,8,9,10]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
my_list = list(range(1000000))

In [8]:
%%timeit #con esto se mide el tiempo de ejecución
my_list2 = [x * 2 for x in my_list]

57.8 ms ± 919 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
my_arr = np.arange(1000000)

In [10]:
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [11]:
%%timeit
my_arr2 = my_arr * 2

847 µs ± 12.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## ¿Qué son los arrays?

- Son "listas" que no pueden cambiar su longitud una vez definida
- Los arrays con más de una dimensión se llaman ndarray, tienen un par de particularidades:
    - Los elementos de un array pueden ser de **cualquier tipo**
    - Los elementos tienen que ser del **mismo tipo**
    - Los elementos se pueden redimensionar, que no cambiar su **size** total.
- Cuando tienen más de una dimensión se llaman ndarrays

In [12]:
# Generamos un array con datos aleatorios de distribución normal (media cero y desviación típica 1), de 4 filas y 2 columnas
data = np.random.randn(4, 2)
data

array([[ 1.1353999 ,  1.44991483],
       [-0.02459596, -1.58408404],
       [ 0.32212295, -1.89901238],
       [-0.02869975,  0.72292903]])

In [18]:
[i*5 for i in [1,2,3,5]]

[5, 10, 15, 25]

In [16]:
np.array([1,2,3,5])

array([1, 2, 3, 5])

Operaciones elemento a elemento

In [19]:
data

array([[ 1.1353999 ,  1.44991483],
       [-0.02459596, -1.58408404],
       [ 0.32212295, -1.89901238],
       [-0.02869975,  0.72292903]])

In [21]:
data * 10

array([[ 11.35399901,  14.4991483 ],
       [ -0.24595964, -15.84084042],
       [  3.22122947, -18.99012384],
       [ -0.28699753,   7.22929025]])

In [22]:
data + data

array([[ 2.2707998 ,  2.89982966],
       [-0.04919193, -3.16816808],
       [ 0.64424589, -3.79802477],
       [-0.05739951,  1.44585805]])

- **No** podemos hacer operaciones entre arrays de distinto tamaño (o tal vez si, [manual](https://numpy.org/doc/stable/user/basics.broadcasting.html), [video explicativo](https://www.youtube.com/watch?v=oG1t3qlzq14))
- Podemos consultar propiedades del array
    - <b>dtype</b>: Tipo del contenido del ndarray.
    - <b>ndim</b>: Número de dimensiones/ejes del ndarray.
    - <b>shape</b>: Estructura/forma del ndarray, es decir, número de elementos en cada uno de los ejes/dimensiones.
    - <b>size</b>: Número total de elementos en el ndarray. 

In [26]:
data[0]

array([1.1353999 , 1.44991483])

In [25]:
data[0]+data

array([[ 2.2707998 ,  2.89982966],
       [ 1.11080394, -0.13416921],
       [ 1.45752285, -0.44909755],
       [ 1.10670015,  2.17284386]])

In [15]:
data.shape

(4, 2)

In [27]:
data.dtype

dtype('float64')

In [28]:
data.ndim

2

In [29]:
data.size

8

## ¿Cómo creamos arrays?

- Existen muchas formas de crear ndarrays en Numpy

<center>
<img src="imgs/np_1.png"  alt="drawing" width="70%"/>
</center>

- Lo podemos crear de forma manual

In [17]:
lista_1 = [1, 2, 3, 4, 5]
array_1 = np.array(lista_1)
array_1

array([1, 2, 3, 4, 5])

In [18]:
lista_2 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
array_2 = np.array(lista_2)
array_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

- Podemos crear un array de ceros

In [30]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

- Podemos crear un array de unos

In [32]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

- Podemos crear arrays "vacíos" que no están realmente vacíos, ya que se les asignan lo que tengan esos espacios de memoria.


In [24]:
np.empty((2, 3, 2))

array([[[9.96307059e-312, 2.47032823e-322],
        [0.00000000e+000, 0.00000000e+000],
        [1.12465777e-312, 1.04082753e-047]],

       [[7.17473174e-091, 8.69517921e-071],
        [1.56108843e+184, 1.17381598e+165],
        [3.99910963e+252, 1.39810814e-076]]])

- Podemos crear arrays con un rango determinado

In [33]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
np.arange(1, 10, 0.5) # (inicio, fin, paso)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

- Podemos generar rangos entre dos valores determinados, indicando la cantidad de elementos que queremos

In [28]:
np.linspace(0, 10, 100) # (inicio, fin, número de puntos)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

- Como hemos comentado los arrays se pueden redimensionar

In [36]:
array = np.arange(21)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [38]:
array.reshape(4, -1)

ValueError: cannot reshape array of size 21 into shape (4,newaxis)

In [4]:
array.reshape(3, 7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [39]:
# si no se especifica el número de filas, se calcula automáticamente
array.reshape(3,-1)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [7]:
# causa error si no se puede calcular el número de filas automáticamente, o si no cuadra con el número de elementos
array.reshape(4,-1)

ValueError: cannot reshape array of size 21 into shape (4,newaxis)

## Indexación 

<center>
<img src="imgs/np_2.png"  alt="drawing" width="70%"/>
</center>

- En ndarrays unidimensionales el funcionamiento es idéntico al que se tiene en secuencias básicas de Python. 
- El primer eje es el de las filas, el segundo eje es el de las columnas,.....

### 1D

In [40]:
array_1d = np.array([1, 2, 3, 4, 5])

In [41]:
print(array_1d.ndim)
print(array_1d.shape)
print(array_1d.size)


1
(5,)
5


In [42]:
print(array_1d)
print(array_1d[0])
print(array_1d[4])
print(array_1d[-1])
print(array_1d[-5])
print(array_1d[1:4])
print(array_1d[1:-1])
print(array_1d[1:])
print(array_1d[:4])
print(array_1d[0:4:2])

[1 2 3 4 5]
1
5
5
1
[2 3 4]
[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3]


### 2D

En ndarrays multidimensionales, existen dos posibles formas de realizar el acceso:<br/>
<ul>
<li><b> Indexación recursiva:</b> array[a:b:c en dim_1][a:b:c en dim_2]...[a:b:c en dim_n]</li>
<li><b> Indexación con comas:</b> array[a:b:c en dim_1, a:b:c en dim_2, ...a:b:c en dim_n]</li>
</ul>

In [43]:
array_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])


In [45]:
array_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [48]:
array_2d[1,2]

8

In [44]:
print(array_2d.ndim)
print(array_2d.shape)
print(array_2d.size)

2
(2, 5)
10


In [49]:
print(array_2d)
print(array_2d[0, 0])
print(array_2d[0, 4])
print(array_2d[1, 0])
print(array_2d[1, 4])
print(array_2d[0, 1:4])
print(array_2d[1, 1:4])
print(array_2d[0:2, 0])
print(array_2d[0:2, 1])
print(array_2d[0:2, 2])
print(array_2d[0:2, 3])
print(array_2d[0:2, 1:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
1
5
6
10
[2 3 4]
[7 8 9]
[1 6]
[2 7]
[3 8]
[4 9]
[[2 3]
 [7 8]]


### 3D

In [50]:
array_3d = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])

In [51]:
print(array_3d.ndim)
print(array_3d.shape)
print(array_3d.size)

3
(2, 2, 5)
20


In [52]:
print(array_3d)
print(array_3d[0, 0, 0])
print(array_3d[0, 1, 0])
print(array_3d[1, 1, 4])
print(array_3d[0, 0, 1:4])
print(array_3d[1, 1, 1:4])
print(array_3d[0:2, 1, 1])
print(array_3d[0:2, :2, 1:3])


[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]
1
6
20
[2 3 4]
[17 18 19]
[ 7 17]
[[[ 2  3]
  [ 7  8]]

 [[12 13]
  [17 18]]]


## Slicing

- El slicing es realizar cortes de nuestros ndarrays en numpy
- Hay que tener cuidado a la hora de hacer un slice.

<center>
<img src="imgs/np_3.png"  alt="drawing" width="30%"/>
</center>

In [53]:
array_1 = np.arange(10)
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Podemos asignar valores a posiciones

In [55]:
array_1[0:4] = 100
array_1

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9])

- Podemos generar un nuevo slice que sea solo una parte de otro. No hace una copia, es una referencia a la otra parte

In [56]:
array_slice = array_1[4:7]
array_slice

array([4, 5, 6])

- Si hacemos un cambio en el slice se cambia el original, y viceversa

In [57]:
array_slice[0] = 50

In [58]:
array_1

array([100, 100, 100, 100,  50,   5,   6,   7,   8,   9])

In [59]:
array_1[5]= 500

In [60]:
array_slice

array([ 50, 500,   6])

- Para solucionar este problema se utiliza el método copy

In [61]:
array_1 = np.arange(10)
array_2 = array_1.copy()
array_1[5]= 500
array_2[0]= 100
print(array_1)
print(array_2)

[  0   1   2   3   4 500   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


## Indexación y Slicing Booleano

- Nos permite realizar indexaciones mediante máscaras booleanas
    - Una máscara booleana es una array que solo contiene True y False (True en las posiciones que nos vamos a quedar y false para las que no)


In [25]:
array_1 = np.arange(10)
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
array_1 > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [62]:
array_1[array_1 > 5]

array([500,   6,   7,   8,   9])

- También se puede usar para un array de texto

In [64]:
nombres = np.array(['Pepe', 'Juan', 'Ana', 'Pepe', 'Juan', 'Ana'])
datos = np.random.randn(6, 4)
nombres

array(['Pepe', 'Juan', 'Ana', 'Pepe', 'Juan', 'Ana'], dtype='<U4')

In [65]:
nombres == 'Pepe'

array([ True, False, False,  True, False, False])

- Como nombres y datos tienen la misma logitud, podemos usar esta máscara en ambos

In [66]:
print(datos)
print('-'*100)
print(datos[nombres == 'Pepe'])

[[-0.45917388 -0.84305057 -1.6009089  -1.02909951]
 [ 0.02737003  0.47987286  0.97379478 -1.54417134]
 [ 0.80338036  0.27975374 -0.89397904  1.06525381]
 [ 0.02194441 -0.78937096  0.59111535 -1.83234635]
 [ 0.36952435 -0.0701198  -3.35340849  1.41219716]
 [-0.77362317 -0.49470213  1.6812521   0.19272079]]
----------------------------------------------------------------------------------------------------
[[-0.45917388 -0.84305057 -1.6009089  -1.02909951]
 [ 0.02194441 -0.78937096  0.59111535 -1.83234635]]


- Un uso de lo anterior sería realizar un filtrado de datos, una corrección de valores...etc

___
## Ejercicios

**1** Crea un vector del 1 al 10 de 3 maneras distintas

In [76]:
np.arange(1,10+1)
np.array(range(1,11))
np.linspace(1,10,10)
np.cumsum(np.ones(10))

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

**2** Crea una matriz de 2 dimensiones de longitud diferente, muestra su tipo y su dimension.

In [81]:
np.array([[2,5,5],[2,5,78]]).shape

(2, 3)

In [78]:
np.array([[2,5],[2,5,78]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

**3** Usando la matriz multidimensional _A_, muestra:
- Los elementos de la primera capa
- De los elementos de la segunda capa, solo la 1ª fila ,y las columnas 2 y 3
- Asigna cada capa a un nuevo array, cambia las posiciones centrales por 0s sin que esto afecte a la matriz _A_

In [82]:
A = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
               [13, 14, 15],
               [16, 17, 18]],
              [[19, 20, 21],
               [22, 23, 24],
               [25, 26, 27]]])
A

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [88]:
# Primera capa:
A[1:]

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [91]:
# 2a capa, primera línea, columnas 2,3:
A[1,0,1:]

array([11, 12])

In [92]:
np.array(A, copy=True)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [94]:
# Nuevo array con elementos centrales = 0:
array_b = A.copy()
array_b[:,1,1]=0
array_b

array([[[ 1,  2,  3],
        [ 4,  0,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13,  0, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22,  0, 24],
        [25, 26, 27]]])